language: python
python:
- '2.7'
- '3.3'
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./python/
- coverage run ./python/test.py
after_success:
- codecov --token=6ce49e65-8526-4cd4-8795-4e94a14feeb5
deploy:
  provider: s3
  access_key_id: AKIAJRA4WL4FXNECOUTQ
  secret_access_key:
    secure: VPNXm0kxnGK2HEWGEWqJZY9gsbIHbBz8lPycLnc+9MP0PAeuI1AfLjWeisxuaKI/FKtFcugrSGlLj8YfYQqtVBqMQWZVU5zEeGyKLNESvlz+6SEOMLF4lZXD69u8++H9RGGOjjCPt4mmMfWMaxTfsXQ9jJ8ZR0zpS92fozP7BLLU+cqVQWXBwND6Pq0G8IhKbznbfqteTZqH4fA4lDQUxgVuJrkYVtB3aPXj8/MZlcGcJB17w7u/Gj7RCwifDdDDbsrkgQuf2SY2ZsY39VGwEKcOeuuzQ3hoB0J6w4B18Lu9wbm2qZoNaG9Yw5Whpeci+ugkxTjK0KZyu4hk07q2t00z6Yh4Wk5704KGsE2f3hGH9HJVT8KQHxw7oAbODUN+/JAmc2PK6xn34+W/DoxNtGzKDV6jzL9haGPLOrg+WCmkSDOgGKzrlarqS6HnPYHCG3JA3KvMvDxHwyI/L/6iMN97j2YH066f3XAGT3BA0uFVWGBani2I2yxL+GbwawcGnsgTQ7w37PSD1UtGymKYZtUGJ0n915Y2H7gJJg0bFfgOa2cIzz+F7N149QIqvtXheM9zodS6XqfZKUZjwpGjYnj37LPr3cHw+jPvVeRxOwWQ16bXkTcaA2qupxlh6LCPafea0m2uYzi/uA6ydiNhoSK0Vm6qFLN9nweOtaISTqA=
  bucket: www.simplewebsite.com
  local-dir: html
  region: us-east-2
